# Generated by Django 2.0.1 on 2018-01-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_games_maker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='player_games',
            new_name='developer_game',
        ),
        migrations.RenameModel(
            old_name='games',
            new_name='game',
        ),
        migrations.RenameModel(
            old_name='developer_games',
            new_name='player_game',
        ),
        migrations.AlterModelOptions(
            name='developer_game',
            options={'ordering': ['userID']},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='highscore',
            options={'ordering': ['playerID']},
        ),
        migrations.AlterModelOptions(
            name='player_game',
            options={'ordering': ['userID']},
        ),
    ]
