# Generated by Django 2.0.1 on 2018-01-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_auto_20180117_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
