# Generated by Django 2.0.1 on 2018-02-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_auto_20180214_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='maker',
            field=models.IntegerField(),
        ),
    ]
