# Generated by Django 2.0.1 on 2018-02-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0008_auto_20180214_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
    ]
