# Generated by Django 2.0.1 on 2018-02-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0010_merge_20180216_1451'),
        ('storeapp', '0010_merge_20180216_1452'),
    ]

    operations = [
    ]
