# Generated by Django 2.0.1 on 2018-02-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0012_auto_20180216_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='developer_game',
        ),
        migrations.AddField(
            model_name='payment',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storeapp.game'),
        ),
    ]
