# Generated by Django 2.0.1 on 2018-02-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0013_auto_20180221_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='game',
        ),
    ]
