# Generated by Django 2.0.1 on 2018-01-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='maker',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
