# Generated by Django 2.0 on 2018-02-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_saved_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_game',
            name='saveName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
