# Generated by Django 2.0.1 on 2018-02-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_auto_20180203_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.IntegerField()),
                ('buyer', models.IntegerField()),
                ('amount', models.FloatField()),
                ('pid', models.IntegerField()),
                ('sid', models.CharField(max_length=255)),
                ('checksum', models.CharField(max_length=255)),
            ],
        ),
    ]
