# Generated by Django 2.0.1 on 2018-02-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='sid',
        ),
    ]
