# Generated by Django 2.0.1 on 2018-02-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0009_game_description'),
        ('storeapp', '0008_remove_payment_sid'),
    ]

    operations = [
    ]
