# Generated by Django 2.0.1 on 2018-02-16 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0011_merge_20180216_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
