# Generated by Django 2.0.1 on 2018-02-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0015_auto_20180225_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_game',
            old_name='game',
            new_name='gameID',
        ),
    ]
