# Generated by Django 2.0.1 on 2018-02-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0016_auto_20180225_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_game',
            name='gameID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.game'),
        ),
    ]
